# ---
# PLUGINS local to kraxli/vim-config
# see: ~/.cache/vim/dein/repos
# ==========================================

# --- Disable plugins from Rafi ---
- {repo: plasticboy/vim-markdown, if: 0}
# - {repo: vimwiki/vimwiki, if: 0}

# --- Lazily loading plugins ---

# -- ColorSchemes --
# see config/theme.vim for speedup config/init.vim
- {repo: kraxli/vim-code-dark, on_cmd: colorscheme codedark}
- {repo: kraxli/papercolor-theme, on_cmd: colorscheme PaperColor}
- {repo: sjl/badwolf, on_cmd: colorscheme badwolf}
# - repo: w0ng/vim-hybrid

- {repo: tpope/vim-repeat, on_map: .}

# qpkorr/vim-renamer
- repo: kraxli/vim-renamer
  on_cmd: Renamer
  hook_add: |
    if has('dos16')||has('dos32')||has('win16')||has('win32')||has('win64')
    \ ||has('win32unix')||has('win95')
      let g:RenamerShowHidden=0
    else
      let g:RenamerShowHidden=1
    endif
    augroup user_project_root
      autocmd!
      autocmd! BufEnter,BufRead * ProjectRootLCD

- repo: dbakker/vim-projectroot
  hook_add: |
    let g:rootmarkers = ['.git', 'dub.json', 'dub.sdl', 'index.md',
    \ 'index.wiki', '.projectroot', '.svn']

- repo: xolox/vim-shell
  on_cmd: Open
  on_map: <F6>
  hook_add: let g:shell_verify_urls = 1

- repo: xolox/vim-misc
  on_source: vim-shell

# -- Management / Tasks / ... ---

- repo: kraxli/vimwiki-task
  on_ft: [imwiki]
  hook_add: let g:vimwiki_folding = 'custom'
  hook_source: |
    setlocal spell spelllang=en,de

# hook_post_source: source $VIMPATH/config_dw_after/plugins/vimwiki.vim

# previously: soywod/kronos.vim
- repo: unfog-io/unfog-vim
  on_cmd: [Unfog]


# -- programming language support --

- repo: JesseKPhillips/d.vim
  on_ft: [d, dlang]


# -------------------------------------------------------
# Completion
# -------------------------------------------------------



