# ---
# PLUGINS local to kraxli/vim-config
# see: ~/.cache/vim/dein/repos
# ==========================================

# --- Disable plugins from Rafi ---
- {repo: rhysd/vim-gfm-syntax, if: 0}
- {repo: neoclide/coc.nvim, if: 0}
- {repo: vimwiki/vimwiki, if: 0}
- {repo: nathanaelkane/vim-indent-guides, if: 0}
# - {repo: kraxli/vim-markdown, if: 0}

# --------------------------------------------------
# Base plugins
# --------------------------------------------------
- repo: pbrisbin/vim-mkdir

- repo: Yggdroot/indentLine
  hook_add: |
    let g:indentLine_char_list = ['¦', '┊']
    let g:indentLine_concealcursor = 'nc'
    let g:indentLine_conceallevel = 2

# let g:indentLine_char_list = ['|', '¦', '┆', '┊'] or ¦, ┆, │, ⎸, ▏, ':'
# let g:indentLine_concealcursor = 'inc'

# --------------------------------------------------
# Lazily loading plugins
# --------------------------------------------------

# - repo: jtratner/vim-flavored-markdown
#   on_ft: [markdown, vimwiki, text, ghmarkdown]

# - repo: fcpg/vim-waikiki
#   on_ft: [markdown, vimwiki, text]

- repo: embear/vim-foldsearch
  on_cmd: [Fw, Fs, Fp, FS, Fl, Fc, Fi, Fd, Fe]
  hook_add: |
    let g:foldsearch_highlight=0
    let g:foldsearch_disable_mappings=1
    nmap  <Leader>fw :Fw<cr>
    nmap  <Leader>fs :Fs<cr>
    nmap  <Leader>fS :FS<cr>
    nmap  <Leader>fl :Fl<cr>
    nmap  <Leader>fi :Fi<cr>
    nmap  <Leader>fd :Fd<cr>
    nmap  <Leader>fe :Fe<cr>

# - repo: /home/dave/.fzf/bin/
#   if: isdirectory('/home/dave/.fzf/bin/')
#   on_cmd: FZF

- repo: junegunn/fzf.vim
  on_cmd: FZF

# -- ColorSchemes --
# see config/theme.vim for speedup config/init.vim
- {repo: tomasiser/vim-code-dark, on_cmd: colorscheme codedark}
- {repo: NLKNguyen/papercolor-theme, on_cmd: colorscheme PaperColor}
- {repo: sjl/badwolf, on_cmd: colorscheme badwolf}

- {repo: tpope/vim-repeat, on_map: .}

# qpkorr/vim-renamer
- repo: kraxli/vim-renamer
  on_cmd: Renamer
  hook_add: |
    if has('dos16')||has('dos32')||has('win16')||has('win32')||has('win64')
    \ ||has('win32unix')||has('win95')
      let g:RenamerShowHidden=0
    else
      let g:RenamerShowHidden=1
    endif

- repo: dbakker/vim-projectroot
  hook_add: |
    let g:rootmarkers = ['.git', 'dub.json', 'dub.sdl', 'index.md',
    \ 'index.wiki', '.projectroot', '.svn']
    augroup user_project_root
      autocmd!
      autocmd! BufEnter,BufRead *.* ProjectRootLCD
    augroup END

- repo: xolox/vim-shell
  on_cmd: Open
  on_map: <F6>
  hook_add: let g:shell_verify_urls = 1

- repo: xolox/vim-misc
  on_source: vim-shell

# -- Management / Tasks / ... ---

- repo: kraxli/markdown-misc
  on_ft: [text, vimwiki, markdown]
  hook_add: |
    let g:markdown_enable_folding = 1
    let g:markdown_mapping_switch_status = '<c-space>'
    let g:markdown_wiki_index_key = '<leader>W'
    let g:markdown_blog_index_key = '<leader>B'
    nmap <silent> th :TasksOpenHi<cr>
    nmap <silent> to :TasksOpen<cr>

# - repo: SidOfc/mkdx
#   on_ft: [markdown, vimwiki, text]
#   hook_add: |
#     let g:mkdx#settings = {
#       \ 'image_extension_pattern': 'a\?png\|jpe\?g\|gif',
#       \ 'restore_visual':          1,
#       \ 'enter':                   { 'enable': 1, 'malformed': 1, 'o': 1,
#       \                              'shifto': 1, 'shift': 0 },
#       \ 'map':                     { 'prefix': '<leader>', 'enable': 1 },
#       \ 'tokens':                  { 'enter': ['-', '*', '>'],
#       \                              'bold': '**', 'italic': '*', 'strike': '',
#       \                              'list': '-', 'fence': '',
#       \                              'header': '#' },
#       \ 'checkbox':                { 'toggles': [' ', '-', 'x'],
#       \                              'update_tree': 2,
#       \                              'initial_state': ' ' },
#       \ 'toc':                     { 'text': "TOC", 'list_token': '-',
#       \                              'update_on_write': 0,
#       \                              'position': 0,
#       \                              'details': {
#       \                                 'enable': 0,
#       \                                 'summary': 'Click to expand {{toc.text}}',
#       \                                 'nesting_level': -1,
#       \                                 'child_count': 5,
#       \                                 'child_summary': 'show {{count}} items'
#       \                              }
#       \                            },
#       \ 'table':                   { 'divider': '|',
#       \                              'header_divider': '-',
#       \                              'align': {
#       \                                 'left':    [],
#       \                                 'center':  [],
#       \                                 'right':   [],
#       \                                 'default': 'center'
#       \                              }
#       \                            },
#       \ 'links':                   { 'external': {
#       \                                 'enable': 0, 'timeout': 3, 'host': '', 'relative': 1,
#       \                                 'user_agent':  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/9001.0.0000.000 vim-mkdx/1.9.1'
#       \                              },
#       \                              'fragment': {
#       \                                 'jumplist': 1,
#       \                                 'complete': 1
#       \                              }
#       \                            },
#       \ 'highlight':               { 'enable': 0 },
#       \ 'auto_update':             { 'enable': 0 },
#       \ 'fold':                    { 'enable':  }
#     \ }

- repo: soywod/kronos.vim
  on_cmd: [Kronos]
  hook_add: |
    command! TimeTracker Kronos

# - repo: unfog-io/unfog-vim
# on_cmd: [Unfog]
#  hook_add: |
#    command! TimeTracker Unfog<cr>

# --------------------------------------------------
# Writing
# --------------------------------------------------

# - repo: masukomi/vim-markdown-folding
#   on_ft: [vimwiki, markdown]
#   hook_add: |
#     let g:markdown_fold_style = 'nested'

- repo: lervag/vimtex
  on_ft: [tex]
  hook_add: |
    let g:tex_flavor='latex'
    let g:vimtex_view_method='zathura'
    let g:vimtex_quickfix_mode=0
    set conceallevel=1
    let g:tex_conceal='abdmg'

- repo: godlygeek/tabular
  on_ft: [markdown, latex, tex]

# - repo: reedes/vim-pencil
#   on_ft: [tex, markdown, vimwiki]

# --------------------------------------------------
# Programming language support
# --------------------------------------------------

- repo: JesseKPhillips/d.vim
  on_ft: [d, dlang, diet]

# -------------------------------------------------------
# Completion
# -------------------------------------------------------

- repo: landaire/deoplete-d
  on_ft: [d, diet]

# -------------------------------------------------------
# Watch
# -------------------------------------------------------

