# ---
# PLUGINS local to kraxli/vim-config
# see: ~/.cache/vim/dein/repos
# ==========================================

# --- Disable plugins from Rafi ---
- {repo: rhysd/vim-gfm-syntax, if: 0}
- {repo: neoclide/coc.nvim, if: 0}
- {repo: vimwiki/vimwiki, if: 0}
- {repo: nathanaelkane/vim-indent-guides, if: 0}

# --------------------------------------------------
# Base plugins
# --------------------------------------------------
- repo: pbrisbin/vim-mkdir

- repo: Yggdroot/indentLine
  hook_add: |
    let g:indentLine_char_list = ['¦', '┊']
    let g:indentLine_concealcursor = 'nc'
    let g:indentLine_conceallevel = 2

# let g:indentLine_char_list = ['|', '¦', '┆', '┊'] or ¦, ┆, │, ⎸, ▏, ':'
# let g:indentLine_concealcursor = 'inc'

# --------------------------------------------------
# Lazily loading plugins
# --------------------------------------------------

# - repo: ryanoasis/vim-devicons
#   if: g:use_vim_devicons
#   hook_add:
#     set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Complete\ 12
#     set encoding=utf-8

#   set guifont=Hack

- repo: fcpg/vim-waikiki
  on_ft: [markdown, vimwiki, text]

- repo: embear/vim-foldsearch
  on_cmd: [Fw, Fs, Fp, FS, Fl, Fc, Fi, Fd, Fe]
  hook_add: |
    let g:foldsearch_highlight=0
    let g:foldsearch_disable_mappings=1
    nmap  <Leader>fw :Fw<cr>
    nmap  <Leader>fs :Fs<cr>
    nmap  <Leader>fS :FS<cr>
    nmap  <Leader>fl :Fl<cr>
    nmap  <Leader>fi :Fi<cr>
    nmap  <Leader>fd :Fd<cr>
    nmap  <Leader>fe :Fe<cr>

# - repo: /home/dave/.fzf/bin/
#   if: isdirectory('/home/dave/.fzf/bin/')
#   on_cmd: FZF

- repo: junegunn/fzf.vim
  on_cmd: FZF

# -- ColorSchemes --
# see config/theme.vim for speedup config/init.vim
- {repo: tomasiser/vim-code-dark, on_cmd: colorscheme codedark}
- {repo: NLKNguyen/papercolor-theme, on_cmd: colorscheme PaperColor}
- {repo: sjl/badwolf, on_cmd: colorscheme badwolf}

- {repo: tpope/vim-repeat, on_map: .}

# qpkorr/vim-renamer
- repo: kraxli/vim-renamer
  on_cmd: Renamer
  hook_add: |
    if has('dos16')||has('dos32')||has('win16')||has('win32')||has('win64')
    \ ||has('win32unix')||has('win95')
      let g:RenamerShowHidden=0
    else
      let g:RenamerShowHidden=1
    endif

- repo: dbakker/vim-projectroot
  hook_add: |
    let g:rootmarkers = ['.git', 'dub.json', 'dub.sdl', 'index.md',
    \ 'index.wiki', '.projectroot', '.svn']
    augroup user_project_root
      autocmd!
      autocmd! BufEnter,BufRead *.* ProjectRootLCD
    augroup END

- repo: xolox/vim-shell
  on_cmd: Open
  on_map: <F6>
  hook_add: let g:shell_verify_urls = 1

- repo: xolox/vim-misc
  on_source: vim-shell

# -- Management / Tasks / ... ---

# - repo: kraxli/vimwiki-task
#   if: 0
#   on_ft: [vimwiki, markdown]
#   hook_add: let g:vimwiki_folding = 'custom'
#   hook_source: |
#     setlocal spell spelllang=en,de

- repo: kraxli/markdown-misc
  on_ft: [text, vimwiki, markdown]
  hook_add: |
    let g:markdown_enable_folding = 1
    let g:markdown_mapping_switch_status = '<c-space>'
    let g:markdown_wiki_index_key = '<leader>W'
    let g:markdown_blog_index_key = '<leader>B'
    nmap <silent> th :TasksOpenHi<cr>
    nmap <silent> to :TasksOpen<cr>

- repo: soywod/kronos.vim
  on_cmd: [Kronos]
  hook_add: |
    command! TimeTracker Kronos

# - repo: unfog-io/unfog-vim
# on_cmd: [Unfog]
#  hook_add: |
#    command! TimeTracker Unfog<cr>

# --------------------------------------------------
# Writing
# --------------------------------------------------

# - repo: masukomi/vim-markdown-folding
#   on_ft: [vimwiki, markdown]
#   hook_add: |
#     let g:markdown_fold_style = 'nested'

- repo: lervag/vimtex
  on_ft: [tex]
  hook_add: |
    let g:tex_flavor='latex'
    let g:vimtex_view_method='zathura'
    let g:vimtex_quickfix_mode=0
    set conceallevel=1
    let g:tex_conceal='abdmg'

- repo: godlygeek/tabular
  on_ft: [markdown, latex, tex]

# - repo: reedes/vim-pencil
#   on_ft: [tex, markdown, vimwiki]

# --------------------------------------------------
# Programming language support
# --------------------------------------------------

- repo: JesseKPhillips/d.vim
  on_ft: [d, dlang, diet]

# -------------------------------------------------------
# Completion
# -------------------------------------------------------

- repo: landaire/deoplete-d
  on_ft: [d, diet]

# -------------------------------------------------------
# Watch
# -------------------------------------------------------

