


# see config/theme.vim for speedup config/init.vim
- repo: kraxli/vim-code-dark
- repo: kraxli/papercolor-theme
- repo: w0ng/vim-hybrid
- repo: sjl/badwolf

- { repo: tpope/vim-repeat, on_map: . }
- { repo: qpkorr/vim-renamer, on_cmd: Renamer }

# --- Lazily loading plugins ---
- repo: dbakker/vim-projectroot
  hook_add: |
    let g:rootmarkers = ['.git', 'dub.json', 'dub.sdl', 'index.md',
    \ 'index.wiki', '.projectroot', '.svn']

- repo: xolox/vim-shell
  on_cmd: Open
  on_map:  <F6>
  hook_add: let g:shell_verify_urls = 1

- repo: xolox/vim-misc
  on_source: vim-shell
